# Generated by Django 5.0.1 on 2024-02-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athlete_journal", "0002_d_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.TextField(null=True)),
                ("drink", models.TextField(null=True)),
                ("time", models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="d_log",
            old_name="user",
            new_name="log_user",
        ),
        migrations.AddField(
            model_name="d_log",
            name="feeling_log",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="recovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_meals", models.IntegerField(null=True)),
                ("sleep_hrs", models.IntegerField(null=True)),
                (
                    "meals",
                    models.ManyToManyField(
                        related_name="fuel", to="athlete_journal.meal"
                    ),
                ),
                (
                    "rec_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rec_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
